
SOURCE_IMAGE = os.getenv("SOURCE_IMAGE", default='harbor.services.tanzu.rocks/workshop/pairname-bootiful-service-source')
LOCAL_PATH = os.getenv("LOCAL_PATH", default='.')
NAMESPACE = os.getenv("NAMESPACE", default='trial')

WORKLOAD_NAME = "bootiful-service-pairname-live-update"

local_resource(
  'service-gradle',
  './gradlew bootJar',
  deps=['src/main', 'build.gradle'],
  auto_init=False)

k8s_custom_deploy(
    'service-workload',
    apply_cmd="tanzu apps workload apply " + WORKLOAD_NAME + " -f config/workload.yaml --update-strategy replace --debug --live-update" +
               " --local-path " + LOCAL_PATH +
               " --source-image " + SOURCE_IMAGE +
               " --namespace " + NAMESPACE +
               " --yes --output yaml",
    delete_cmd="tanzu apps workload delete " + WORKLOAD_NAME + " -f config/workload.yaml --namespace " + NAMESPACE + " --yes",
    container_selector='workload',

    deps=['build.gradle', './build/classes/java/main', './build/resources/main'],
    live_update=[
       sync('./build/classes/java/main', '/workspace/BOOT-INF/classes'),
       sync('./build/resources/main', '/workspace/BOOT-INF/classes')
    ]
)

k8s_resource('service-workload', port_forwards=["8080:8080"],
            extra_pod_selectors=[{'carto.run/workload-name': WORKLOAD_NAME, 'app.kubernetes.io/component': 'run'}])
